worldplotCat(data = testdata1b,
             div = 1,
             ColName = "VCat",
             CountryName = "Cshort",
             CountryNameType = "isoa2",
             title = "Testing the function for Categorical variables",
             Categories = c("Low", "Average", "High"),
             legendTitle = "CAT",
             annote = TRUE)
